version: "3"

services:
  etus_reverse_proxy:
    image: nginx:stable-alpine
    container_name: etus_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
    volumes:
      - .docker/nginx:/etc/nginx/conf.d
      - ./application:/var/www/html
  etus_php:
    container_name: etus_php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    ports:
      - "9000:9000"
    environment:
      APP_NAME: "laravel"
    volumes:
      - ./application:/var/www/html
      - ./logs/:/var/log
    depends_on:
      - etus_db
      - etus_reverse_proxy
    networks:
      - internal
  etus_vue:
    container_name: etus_vue
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - internal
    environment:
      VITE_API_HOST: ""
  etus_db:
    container_name: etus_db
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "public"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASS: "password"
    volumes:
      - /var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge
