version: "3"

services:
  webserver:
    image: nginx:stable-alpine
    container_name: reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
    volumes:
      - .docker/nginx:/etc/nginx/conf.d
      - ./application:/var/www/html
  php:
    container_name: php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    ports:
      - "9000:9000"
    environment:
      APP_NAME: "laravel"
    volumes:
      - ./application:/var/www/html
      - ./logs/php.log/:/var/log/fpm-php.www.log
    depends_on:
      - mysql
      - webserver
    networks:
      - internal
  mysql:
    container_name: db
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "public"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASS: "password"
    volumes:
      - /var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge
